[package]
name = "poliosis-test"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.28.6"
wgpu = "0.16.1"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
regex = "1"
wgpu_glyph = "0.20"
chrono = "0.4"
rodio = "0.17.1"